version: "3.9"

services:
  portfolio:
    build:
      context: ./portfolio
    ports:
      - "3000:3000"
    depends_on:
      - forum

  ascii-art-web:
    build:
      context: ./projects/ascii-art-web
    ports:
      - "8080:8080"

  forum:
    build:
      context: ./projects/forum
    ports:
      - "8081:8080"
